'use client';
import { useState } from 'react';
import { RandomFox } from '@/components/RandomFox';

const random = () => Math.floor(Math.random() * 123 + 1);
const generateId = () => new Date().getTime().toString();

type ImageItem = Array<{
  id: string;
  url: string;
}>;

export default function Home() {
  const [images, setImages] = useState<ImageItem>([
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
  ]);

  console.log(images);

  return (
    <>
      <head>
        <title>TypeScript & React</title>
        <meta
          name="description"
          content="Generated by YilmarDev with a Platzi Course"
        />
        <link rel="icon" type="image/x-icon" href="./favicon.ico" />
      </head>
      <body>
        <main>
          <h1 className="text-3xl font-bold underline">
            Hello Platzi and TypeScript
          </h1>

          {images.map(({ id, url }) => (
            <div key={id} className="p-4">
              <RandomFox image={url} alt="Random fox to display" />
            </div>
          ))}

          <footer>By YilmarDev</footer>
        </main>
      </body>
    </>
  );
}
