'use client';
import { useState } from 'react';
import { random } from 'lodash';
import type { MouseEventHandler } from 'react';
import { LazyImage } from '@/components/LazyImage';

const generateRandomNumber = () => random(1, 123);
const generateId = () => random(1, 2000).toString();

export default function Home() {
  const [images, setImages] = useState<IImageItem[]>([]);

  const addNewImage: MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImage: IImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg`,
    };

    setImages([...images, newImage]);
  };

  return (
    <>
      <head>
        <title>TypeScript & React</title>
        <meta
          name="description"
          content="Generated by YilmarDev with a Platzi Course"
        />
        <link rel="icon" type="image/x-icon" href="./favicon.ico" />
      </head>
      <body>
        <main>
          <h1 className="text-3xl font-bold underline">
            Hello Platzi and TypeScript
          </h1>

          <button type="button" onClick={addNewImage}>
            Add fox
          </button>

          {images.map(({ id, url }, index) => (
            <div key={id} className="p-4">
              <LazyImage
                src={url}
                alt="Random fox to display"
                width={320}
                height="auto"
                onClick={() => console.log('Hola desde page')}
                onLazyLoad={(img: HTMLImageElement) => {
                  console.log(`Image #${index + 1} cargada. Nodo:`, img);
                }}
              />
            </div>
          ))}

          <footer>By YilmarDev</footer>
        </main>
      </body>
    </>
  );
}
